<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Delivery Log</title>

    <style>
        * { box-sizing: border-box; }
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 13px;
            color: #333;
            margin: 20px;
        }
        .header-section {
            border-bottom: 2px solid #060e57;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }
        .logo {
            max-height: 60px;
        }
        .company-info {
            text-align: right;
            font-size: 13px;
            line-height: 1.5;
        }
        .title {
            text-align: center;
            font-size: 20px;
            color: #06069a;
            margin-bottom: 10px;
            margin-top: -10px;
        }
        .sub-title {
            text-align: center;
            font-size: 13px;
            color: #444;
            margin-bottom: 20px;
        }

        /* TABLE */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 25px;
        }
        th, td {
            border: 1px solid #ccc;
            padding: 7px;
        }
        th {
            background-color: #19196e;
            color: white;
            font-size: 13px;
        }
        td {
            font-size: 12px;
        }

        /* BADGE */
        .status-success {
            background: #28a745;
            color: white;
            padding: 3px 6px;
            border-radius: 4px;
            font-size: 12px;
        }
        .status-danger {
            background: #dc3545;
            color: white;
            padding: 3px 6px;
            border-radius: 4px;
            font-size: 12px;
        }

        .footer {
            font-size: 12px;
            text-align: right;
            margin-top: 40px;
            color: #777;
        }

        .watermark {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-30deg);
            font-size: 60px;
            color: #cccccc;
            opacity: 0.2;
            z-index: -1;
            pointer-events: none;
            font-weight: bold;
            white-space: nowrap;
        }
    </style>

</head>
<body>

<!-- Watermark -->
<div class="watermark">{{ $company->company_name }}</div>

<!-- Header -->
<div class="header-section">
    <table style="width: 100%;">
        <tr>
            <td style="width: 55%;">
                @if(!empty($company->logo))
                   <img src="{{ url($company->logo) }}" class="logo" alt="Logo">
                @else
                    <strong style="font-size: 20px;">{{ $company->company_name }}</strong>
                @endif
            </td>

            <td class="company-info">
                <strong>{{ $company->company_name }}</strong><br>
                Phone: {{ $company->phone_code.$company->company_pnone }}<br>
                Email: {{ $company->company_email }}<br>
                Address: {{ $company->address }}
            </td>
        </tr>
    </table>
</div>

<!-- Title -->
<div class="title">Email Delivery Report</div>
<div class="sub-title">
    Generated On: {{ now()->format('d M Y, h:i A') }}
</div>

<!-- DATA TABLE -->
<table>
    <thead>
        <tr>
            <th width="5%">ID</th>
            <th width="20%">Email</th>
            <th width="25%">Subject</th>
            <th width="10%">Status</th>
            <th width="15%">Created</th>
            <th width="15%">Sent</th>
        </tr>
    </thead>

    <tbody>
        @foreach($logs as $log)
            <tr>
                <td>{{ $log->id }}</td>
                <td>{{ $log->email }}</td>
                <td>{{ \Illuminate\Support\Str::limit($log->subject, 35) }}</td>

                <td>
                    @if($log->status == 1)
                        <span class="status-success">Delivered</span>
                    @else
                        <span class="status-danger">Pending</span>
                    @endif
                </td>

                <td>{{ $log->created_at }}</td>
                <td>{{ $log->updated_at }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

<!-- Footer -->
<div class="footer">
    Report generated by <b>{{ $company->company_name }}</b>
</div>

</body>
</html>
